from PyQt5 import QtCore, QtGui, QtWidgets

def graphicsInterf2(form, window, size):
	w = size.width()
	h = size.height()
	window.resize(w, h)
	window.move(0, 0)
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	window.setFont(font)
	window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	window.setIconSize(QtCore.QSize(800, 800))
	window.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
	form.centralwidget.setObjectName("centralwidget")
	form.label.setEnabled(True)
	form.label.setGeometry(QtCore.QRect(0, 0, 80, 60))
	font = QtGui.QFont()
	font.setPointSize(32)
	form.label.setFont(font)
	form.label.setTextFormat(QtCore.Qt.PlainText)
	form.label.setAlignment(QtCore.Qt.AlignCenter)
	form.label.setObjectName("label")
	form.label_2.setGeometry(QtCore.QRect(0, 60, 80, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_2.setFont(font)
	form.label_2.setAlignment(QtCore.Qt.AlignCenter)
	form.label_2.setObjectName("label_2")
	form.label_3.setGeometry(QtCore.QRect(0, 170, 80, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_3.setFont(font)
	form.label_3.setAlignment(QtCore.Qt.AlignCenter)
	form.label_3.setObjectName("label_3")
	form.enter_purchase_button.setGeometry(QtCore.QRect(50, 660, 350, 51))
	font = QtGui.QFont()
	font.setPointSize(24)
	form.enter_purchase_button.setFont(font)
	form.enter_purchase_button.setObjectName("enter_purchase_button")
	form.lineEdit.setGeometry(QtCore.QRect(300, 110, 200, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.lineEdit.setFont(font)
	form.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
	form.lineEdit.setObjectName("lineEdit")
	form.item_list.setEnabled(True)
	form.item_list.setGeometry(QtCore.QRect(20, 230, 150, 400))
	form.item_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	form.item_list.setFont(font)
	form.item_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.item_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.item_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.item_list.setAlternatingRowColors(True)
	form.item_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.item_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.item_list.setObjectName("item_list")
	form.calendarWidget.setGeometry(QtCore.QRect(380, 230, 400, 400))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.calendarWidget.setFont(font)
	form.calendarWidget.setObjectName("calendarWidget")
	form.show_all_button.setGeometry(QtCore.QRect(450, 660, 300, 50))
	font = QtGui.QFont()
	font.setPointSize(24)
	font.setBold(False)
	font.setWeight(50)
	form.show_all_button.setFont(font)
	form.show_all_button.setObjectName("show_all_button")
	form.toolButton.setGeometry(QtCore.QRect(720, 10, 50, 50))
	form.toolButton.setAutoFillBackground(True)
	icon = QtGui.QIcon()
	icon.addPixmap(QtGui.QPixmap("tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	form.toolButton.setIcon(icon)
	form.toolButton.setIconSize(QtCore.QSize(50, 50))
	form.toolButton.setShortcut("")
	form.toolButton.setAutoRepeat(False)
	form.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
	form.toolButton.setAutoRaise(True)
	form.toolButton.setObjectName("toolButton")
	form.card_list = QtWidgets.QListWidget(form.centralwidget)
	form.card_list.setEnabled(True)
	form.card_list.setGeometry(QtCore.QRect(200, 230, 150, 400))
	form.card_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.card_list.setFont(font)
	form.card_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.card_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.card_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.card_list.setAlternatingRowColors(True)
	form.card_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.card_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.card_list.setObjectName("card_list")
	item = QtWidgets.QListWidgetItem()
	form.card_list.addItem(item)
	form.item_list.raise_()
	form.label.raise_()
	form.label_2.raise_()
	form.label_3.raise_()
	form.enter_purchase_button.raise_()
	form.lineEdit.raise_()
	form.calendarWidget.raise_()
	form.show_all_button.raise_()
	form.toolButton.raise_()
	form.card_list.raise_()
	window.setCentralWidget(form.centralwidget)
	form.menubar = QtWidgets.QMenuBar(window)
	form.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
	form.menubar.setObjectName("menubar")
	window.setMenuBar(form.menubar)
	form.statusbar = QtWidgets.QStatusBar(window)
	form.statusbar.setObjectName("statusbar")
	window.setStatusBar(form.statusbar)

	form.retranslateUi(window)
	form.item_list.setCurrentRow(-1)
	form.card_list.setCurrentRow(-1)
	QtCore.QMetaObject.connectSlotsByName(window)


def graphicsInterfShow(form, window, size):
	w = size.width()
	h = size.height()
	window.resize(w, h)
	window.move(0, 0)
	window.setIconSize(QtCore.QSize(w, h))
	form.calendarWidget.setGeometry(QtCore.QRect(w * 0.6, h * 0.2, w * 0.35, h * 0.42))
	form.add_purchase_button.setGeometry(QtCore.QRect(w * 0.635, h * 0.7, 550, 100))
	form.textEdit.setGeometry(QtCore.QRect(w * 0.4, h * 0.2, w * 0.18, h * 0.42))
	form.toolButton.setGeometry(QtCore.QRect(w * 0.95, 10, 50, 100))
	form.toolButton.setIconSize(QtCore.QSize(50, 50))
	form.label_2.setGeometry(QtCore.QRect(w * 0.35, 10, w * 0.3, 100))
	form.graphic.setGeometry(QtCore.QRect(w * 0.05, h * 0.2, w * 0.33, h * 0.42))
	form.graph_purchase_button.setGeometry(QtCore.QRect(w * 0.08, h * 0.7, 200, 100))
	form.graph_income_button.setGeometry(QtCore.QRect(w * 0.25, h * 0.7, 200, 100))
	form.menubar.setGeometry(QtCore.QRect(0, 0, 800, 100))#???????


def graphicsInterfTool(form, window, size):
	w = size.width()
	h = size.height()
	window.resize(w, h)
	window.move(0, 0)
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	window.setFont(font)
	window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	window.setIconSize(QtCore.QSize(800, 800))
	window.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
	form.centralwidget.setObjectName("centralwidget")
	form.label.setEnabled(True)
	form.label.setGeometry(QtCore.QRect(0, 0, 800, 60))
	font = QtGui.QFont()
	font.setPointSize(32)
	form.label.setFont(font)
	form.label.setTextFormat(QtCore.Qt.PlainText)
	form.label.setAlignment(QtCore.Qt.AlignCenter)
	form.label.setObjectName("label")
	form.label_3.setGeometry(QtCore.QRect(239, 60, 501, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_3.setFont(font)
	form.label_3.setAlignment(QtCore.Qt.AlignCenter)
	form.label_3.setObjectName("label_3")
	form.item_list.setEnabled(True)
	form.item_list.setGeometry(QtCore.QRect(50, 70, 190, 160))
	form.item_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.item_list.setFont(font)
	form.item_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.item_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.item_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.item_list.setAlternatingRowColors(True)
	form.item_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.item_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.item_list.setObjectName("item_list")
	form.show_all_button.setGeometry(QtCore.QRect(250, 680, 300, 60))
	font = QtGui.QFont()
	font.setPointSize(24)
	font.setBold(False)
	font.setWeight(50)
	form.show_all_button.setFont(font)
	form.show_all_button.setObjectName("show_all_button")
	form.add_item_button.setGeometry(QtCore.QRect(590, 110, 150, 51))
	font = QtGui.QFont()
	font.setPointSize(20)
	form.add_item_button.setFont(font)
	form.add_item_button.setObjectName("add_item_button")
	form.add_item_field.setGeometry(QtCore.QRect(300, 110, 221, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.add_item_field.setFont(font)
	form.add_item_field.setAlignment(QtCore.Qt.AlignCenter)
	form.add_item_field.setObjectName("add_item_field")
	form.list_card.setEnabled(True)
	form.list_card.setGeometry(QtCore.QRect(50, 270, 190, 160))
	form.list_card.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.list_card.setFont(font)
	form.list_card.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.list_card.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.list_card.setFrameShadow(QtWidgets.QFrame.Plain)
	form.list_card.setAlternatingRowColors(True)
	form.list_card.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.list_card.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.list_card.setObjectName("list_card")
	form.add_card_field.setGeometry(QtCore.QRect(300, 310, 231, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.add_card_field.setFont(font)
	form.add_card_field.setAlignment(QtCore.Qt.AlignCenter)
	form.add_card_field.setObjectName("add_card_field")
	form.add_card_button.setGeometry(QtCore.QRect(590, 310, 150, 51))
	font = QtGui.QFont()
	font.setPointSize(20)
	form.add_card_button.setFont(font)
	form.add_card_button.setObjectName("add_card_button")
	form.card_list.setGeometry(QtCore.QRect(239, 260, 501, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.card_list.setFont(font)
	form.card_list.setAlignment(QtCore.Qt.AlignCenter)
	form.card_list.setObjectName("card_list")
	form.delete_card_button.setGeometry(QtCore.QRect(590, 380, 150, 51))
	font = QtGui.QFont()
	font.setPointSize(20)
	form.delete_card_button.setFont(font)
	form.delete_card_button.setObjectName("delete_card_button")
	form.label_5.setGeometry(QtCore.QRect(239, 370, 351, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_5.setFont(font)
	form.label_5.setAlignment(QtCore.Qt.AlignCenter)
	form.label_5.setObjectName("label_5")
	form.label_6.setGeometry(QtCore.QRect(239, 170, 351, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_6.setFont(font)
	form.label_6.setAlignment(QtCore.Qt.AlignCenter)
	form.label_6.setObjectName("label_6")
	form.delete_item_button.setGeometry(QtCore.QRect(590, 180, 150, 51))
	font = QtGui.QFont()
	font.setPointSize(20)
	form.delete_item_button.setFont(font)
	form.delete_item_button.setObjectName("delete_item_button")
	form.income_list.setEnabled(True)
	form.income_list.setGeometry(QtCore.QRect(50, 470, 190, 170))
	form.income_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.income_list.setFont(font)
	form.income_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.income_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.income_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.income_list.setAlternatingRowColors(True)
	form.income_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.income_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.income_list.setObjectName("income_list")
	form.card_list_2.setGeometry(QtCore.QRect(239, 460, 501, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.card_list_2.setFont(font)
	form.card_list_2.setAlignment(QtCore.Qt.AlignCenter)
	form.card_list_2.setObjectName("card_list_2")
	form.add_income_field.setGeometry(QtCore.QRect(300, 510, 231, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.add_income_field.setFont(font)
	form.add_income_field.setAlignment(QtCore.Qt.AlignCenter)
	form.add_income_field.setObjectName("add_income_field")
	form.add_income_button.setGeometry(QtCore.QRect(590, 510, 150, 51))
	font = QtGui.QFont()
	font.setPointSize(20)
	form.add_income_button.setFont(font)
	form.add_income_button.setObjectName("add_income_button")
	form.delete_income_button.setGeometry(QtCore.QRect(590, 580, 150, 51))
	font = QtGui.QFont()
	font.setPointSize(20)
	form.delete_income_button.setFont(font)
	form.delete_income_button.setObjectName("delete_income_button")
	form.card_list_3.setGeometry(QtCore.QRect(259, 570, 331, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.card_list_3.setFont(font)
	form.card_list_3.setAlignment(QtCore.Qt.AlignCenter)
	form.card_list_3.setObjectName("card_list_3")
	form.card_list_4.setGeometry(QtCore.QRect(238, 590, 351, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.card_list_4.setFont(font)
	form.card_list_4.setAlignment(QtCore.Qt.AlignCenter)
	form.card_list_4.setObjectName("card_list_4")
	form.card_list_5.setGeometry(QtCore.QRect(240, 390, 351, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.card_list_5.setFont(font)
	form.card_list_5.setAlignment(QtCore.Qt.AlignCenter)
	form.card_list_5.setObjectName("card_list_5")
	form.card_list_6.setGeometry(QtCore.QRect(240, 190, 351, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.card_list_6.setFont(font)
	form.card_list_6.setAlignment(QtCore.Qt.AlignCenter)
	form.card_list_6.setObjectName("card_list_6")
	form.item_list.raise_()
	form.label.raise_()
	form.label_3.raise_()
	form.show_all_button.raise_()
	form.add_item_button.raise_()
	form.add_item_field.raise_()
	form.list_card.raise_()
	form.add_card_field.raise_()
	form.add_card_button.raise_()
	form.card_list.raise_()
	form.delete_card_button.raise_()
	form.label_5.raise_()
	form.label_6.raise_()
	form.delete_item_button.raise_()
	form.income_list.raise_()
	form.card_list_2.raise_()
	form.add_income_field.raise_()
	form.add_income_button.raise_()
	form.delete_income_button.raise_()
	form.card_list_3.raise_()
	form.card_list_4.raise_()
	form.card_list_5.raise_()
	form.card_list_6.raise_()
	window.setCentralWidget(form.centralwidget)
	form.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
	form.menubar.setObjectName("menubar")
	window.setMenuBar(form.menubar)
	form.statusbar.setObjectName("statusbar")
	window.setStatusBar(form.statusbar)

	form.retranslateUi(window)
	form.item_list.setCurrentRow(-1)
	form.list_card.setCurrentRow(-1)
	form.income_list.setCurrentRow(-1)
	QtCore.QMetaObject.connectSlotsByName(window)


def graphicsInterfW(window, size):
	window.resize(size.width(), size.height())


def graphicsInterfInc(form, window, size):
	w = size.width()
	h = size.height()
	window.resize(w, h)
	window.move(0, 0)
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	window.setFont(font)
	window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	window.setIconSize(QtCore.QSize(800, 800))
	window.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
	form.centralwidget.setObjectName("centralwidget")
	form.label.setEnabled(True)
	form.label.setGeometry(QtCore.QRect(0, 0, 800, 60))
	font = QtGui.QFont()
	font.setPointSize(32)
	form.label.setFont(font)
	form.label.setTextFormat(QtCore.Qt.PlainText)
	form.label.setAlignment(QtCore.Qt.AlignCenter)
	form.label.setObjectName("label")
	form.label_2.setGeometry(QtCore.QRect(0, 60, 800, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_2.setFont(font)
	form.label_2.setAlignment(QtCore.Qt.AlignCenter)
	form.label_2.setObjectName("label_2")
	form.label_3.setGeometry(QtCore.QRect(0, 170, 800, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_3.setFont(font)
	form.label_3.setAlignment(QtCore.Qt.AlignCenter)
	form.label_3.setObjectName("label_3")
	font = QtGui.QFont()
	font.setPointSize(24)
	form.enter_income_button.setGeometry(QtCore.QRect(50, 660, 350, 51))
	form.enter_income_button.setFont(font)
	form.enter_income_button.setObjectName("enter_income_button")
	form.lineEdit.setGeometry(QtCore.QRect(300, 110, 200, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.lineEdit.setFont(font)
	form.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
	form.lineEdit.setObjectName("lineEdit")
	form.income_list.setEnabled(True)
	form.income_list.setGeometry(QtCore.QRect(30, 230, 150, 400))
	form.income_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.income_list.setFont(font)
	form.income_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.income_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.income_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.income_list.setAlternatingRowColors(True)
	form.income_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.income_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.income_list.setObjectName("income_list")
	form.calendarWidget.setGeometry(QtCore.QRect(370, 230, 400, 400))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.calendarWidget.setFont(font)
	form.calendarWidget.setObjectName("calendarWidget")
	form.show_all_button.setGeometry(QtCore.QRect(450, 660, 300, 50))
	font = QtGui.QFont()
	font.setPointSize(24)
	font.setBold(False)
	font.setWeight(50)
	form.show_all_button.setFont(font)
	form.show_all_button.setObjectName("show_all_button")
	form.toolButton.setGeometry(QtCore.QRect(720, 10, 50, 50))
	form.toolButton.setAutoFillBackground(True)
	icon = QtGui.QIcon()
	icon.addPixmap(QtGui.QPixmap("tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	form.toolButton.setIcon(icon)
	form.toolButton.setIconSize(QtCore.QSize(50, 50))
	form.toolButton.setShortcut("")
	form.toolButton.setAutoRepeat(False)
	form.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
	form.toolButton.setAutoRaise(True)
	form.toolButton.setObjectName("toolButton")
	form.card_list.setEnabled(True)
	form.card_list.setGeometry(QtCore.QRect(200, 230, 150, 400))
	form.card_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.card_list.setFont(font)
	form.card_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.card_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.card_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.card_list.setAlternatingRowColors(True)
	form.card_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.card_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.card_list.setObjectName("card_list")
	form.income_list.raise_()
	form.label.raise_()
	form.label_2.raise_()
	form.label_3.raise_()
	form.enter_income_button.raise_()
	form.lineEdit.raise_()
	form.calendarWidget.raise_()
	form.show_all_button.raise_()
	form.toolButton.raise_()
	form.card_list.raise_()
	window.setCentralWidget(form.centralwidget)
	form.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
	form.menubar.setObjectName("menubar")
	window.setMenuBar(form.menubar)
	form.statusbar.setObjectName("statusbar")
	window.setStatusBar(form.statusbar)

	form.retranslateUi(window)
	form.income_list.setCurrentRow(-1)
	form.card_list.setCurrentRow(-1)
	QtCore.QMetaObject.connectSlotsByName(window)