from PyQt5 import QtCore, QtGui, QtWidgets

def graphicsInterf2(form, window, size):
	window.resize(size.width(), size.height())
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	window.setFont(font)
	window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	window.setIconSize(QtCore.QSize(800, 800))
	window.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
	form.centralwidget.setObjectName("centralwidget")
	form.label.setEnabled(True)
	form.label.setGeometry(QtCore.QRect(0, 0, 80, 60))
	font = QtGui.QFont()
	font.setPointSize(32)
	form.label.setFont(font)
	form.label.setTextFormat(QtCore.Qt.PlainText)
	form.label.setAlignment(QtCore.Qt.AlignCenter)
	form.label.setObjectName("label")
	form.label_2.setGeometry(QtCore.QRect(0, 60, 80, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_2.setFont(font)
	form.label_2.setAlignment(QtCore.Qt.AlignCenter)
	form.label_2.setObjectName("label_2")
	form.label_3.setGeometry(QtCore.QRect(0, 170, 80, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.label_3.setFont(font)
	form.label_3.setAlignment(QtCore.Qt.AlignCenter)
	form.label_3.setObjectName("label_3")
	form.enter_purchase_button.setGeometry(QtCore.QRect(50, 660, 350, 51))
	font = QtGui.QFont()
	font.setPointSize(24)
	form.enter_purchase_button.setFont(font)
	form.enter_purchase_button.setObjectName("enter_purchase_button")
	form.lineEdit.setGeometry(QtCore.QRect(300, 110, 200, 50))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.lineEdit.setFont(font)
	form.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
	form.lineEdit.setObjectName("lineEdit")
	form.item_list.setEnabled(True)
	form.item_list.setGeometry(QtCore.QRect(20, 230, 150, 400))
	form.item_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	form.item_list.setFont(font)
	form.item_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.item_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.item_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.item_list.setAlternatingRowColors(True)
	form.item_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.item_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.item_list.setObjectName("item_list")
	form.calendarWidget.setGeometry(QtCore.QRect(380, 230, 400, 400))
	font = QtGui.QFont()
	font.setPointSize(16)
	form.calendarWidget.setFont(font)
	form.calendarWidget.setObjectName("calendarWidget")
	form.show_all_button.setGeometry(QtCore.QRect(450, 660, 300, 50))
	font = QtGui.QFont()
	font.setPointSize(24)
	font.setBold(False)
	font.setWeight(50)
	form.show_all_button.setFont(font)
	form.show_all_button.setObjectName("show_all_button")
	form.toolButton.setGeometry(QtCore.QRect(720, 10, 50, 50))
	form.toolButton.setAutoFillBackground(True)
	icon = QtGui.QIcon()
	icon.addPixmap(QtGui.QPixmap("tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	form.toolButton.setIcon(icon)
	form.toolButton.setIconSize(QtCore.QSize(50, 50))
	form.toolButton.setShortcut("")
	form.toolButton.setAutoRepeat(False)
	form.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
	form.toolButton.setAutoRaise(True)
	form.toolButton.setObjectName("toolButton")
	form.card_list = QtWidgets.QListWidget(form.centralwidget)
	form.card_list.setEnabled(True)
	form.card_list.setGeometry(QtCore.QRect(200, 230, 150, 400))
	form.card_list.setMinimumSize(QtCore.QSize(101, 0))
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	form.card_list.setFont(font)
	form.card_list.setLayoutDirection(QtCore.Qt.LeftToRight)
	form.card_list.setFrameShape(QtWidgets.QFrame.StyledPanel)
	form.card_list.setFrameShadow(QtWidgets.QFrame.Plain)
	form.card_list.setAlternatingRowColors(True)
	form.card_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
	form.card_list.setLayoutMode(QtWidgets.QListView.SinglePass)
	form.card_list.setObjectName("card_list")
	item = QtWidgets.QListWidgetItem()
	form.card_list.addItem(item)
	form.item_list.raise_()
	form.label.raise_()
	form.label_2.raise_()
	form.label_3.raise_()
	form.enter_purchase_button.raise_()
	form.lineEdit.raise_()
	form.calendarWidget.raise_()
	form.show_all_button.raise_()
	form.toolButton.raise_()
	form.card_list.raise_()
	window.setCentralWidget(form.centralwidget)
	form.menubar = QtWidgets.QMenuBar(window)
	form.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
	form.menubar.setObjectName("menubar")
	window.setMenuBar(form.menubar)
	form.statusbar = QtWidgets.QStatusBar(window)
	form.statusbar.setObjectName("statusbar")
	window.setStatusBar(form.statusbar)

	form.retranslateUi(window)
	form.item_list.setCurrentRow(-1)
	form.card_list.setCurrentRow(-1)
	QtCore.QMetaObject.connectSlotsByName(window)


def graphicsInterfShow(form, window, size):
	window.resize(size.width(), size.height())
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	window.setFont(font)
	window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	window.setIconSize(QtCore.QSize(800, 800))

	form.centralwidget.setObjectName("centralwidget")
	form.calendarWidget.setGeometry(QtCore.QRect(350, 100, 400, 500))
	form.calendarWidget.setObjectName("calendarWidget")
	form.add_purchase_button.setGeometry(QtCore.QRect(30, 640, 350, 60))
	sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	sizePolicy.setHorizontalStretch(0)
	sizePolicy.setVerticalStretch(0)
	sizePolicy.setHeightForWidth(form.add_purchase_button.sizePolicy().hasHeightForWidth())
	form.add_purchase_button.setSizePolicy(sizePolicy)
	font = QtGui.QFont()
	font.setPointSize(24)
	form.add_purchase_button.setFont(font)
	form.add_purchase_button.setObjectName("add_purchase_button")
	form.textEdit.setGeometry(QtCore.QRect(50, 150, 250, 400))
	form.textEdit.setObjectName("textEdit")
	form.toolButton.setGeometry(QtCore.QRect(720, 10, 50, 50))
	form.toolButton.setAutoFillBackground(True)
	icon = QtGui.QIcon()
	icon.addPixmap(QtGui.QPixmap("tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	form.toolButton.setIcon(icon)
	form.toolButton.setIconSize(QtCore.QSize(50, 50))
	form.toolButton.setShortcut("")
	form.toolButton.setAutoRepeat(False)
	form.toolButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
	form.toolButton.setAutoRaise(True)
	form.toolButton.setObjectName("toolButton")
	form.label_2.setEnabled(True)
	form.label_2.setGeometry(QtCore.QRect(100, 0, 600, 60))
	font = QtGui.QFont()
	font.setPointSize(32)
	form.label_2.setFont(font)
	form.label_2.setTextFormat(QtCore.Qt.PlainText)
	form.label_2.setAlignment(QtCore.Qt.AlignCenter)
	form.label_2.setObjectName("label_2")
	form.add_income_button.setGeometry(QtCore.QRect(420, 640, 350, 60))
	sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	sizePolicy.setHorizontalStretch(0)
	sizePolicy.setVerticalStretch(0)
	sizePolicy.setHeightForWidth(form.add_income_button.sizePolicy().hasHeightForWidth())
	form.add_income_button.setSizePolicy(sizePolicy)
	font = QtGui.QFont()
	font.setPointSize(24)
	form.add_income_button.setFont(font)
	form.add_income_button.setObjectName("add_income_button")
	window.setCentralWidget(form.centralwidget)
	form.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
	form.menubar.setObjectName("menubar")
	window.setMenuBar(form.menubar)
	form.statusbar.setObjectName("statusbar")
	window.setStatusBar(form.statusbar)
	form.retranslateUi(window)
	QtCore.QMetaObject.connectSlotsByName(window)


def graphicsInterfTool(window, size):
	window.resize(size.width(), size.height())
	font = QtGui.QFont()
	font.setFamily("Segoe Print")
	font.setPointSize(16)
	window.setFont(font)
	window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	window.setIconSize(QtCore.QSize(800, 800))
	window.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)



def graphicsInterfW(window, size):
	window.resize(size.width(), size.height())


def graphicsInterfInc(window, size):
	window.resize(size.width(), size.height())