# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interf_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.add_purchase_button = QtWidgets.QPushButton(self.centralwidget)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.add_income_button = QtWidgets.QPushButton(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_purchase_button.setText(_translate("MainWindow", "Добавить покупку"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Financial analyser"))
        self.add_income_button.setText(_translate("MainWindow", "Добавить доход"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
